Django_hw/quotes_site/quotes/urls.py
from django.urls import path

from . import views

app_name = "quotes"

urlpatterns = [
    path("", views.home, name="home"),
    path("quotes/", views.show_quotes, name="quotes"),
    path('quotes/<int:page>', views.show_quotes, name="quotes_paginate"),
    path("quotes/add_author/", views.add_author, name="add_author"),
    path("quotes/add_quote/", views.add_quote, name="add_quote"),
    path("quotes/show_author/<int:aut_id>/", views.show_author, name="show_author"),
    path("quotes/show_author/all_quotes_autor/<int:aut_id><int:page>", views.all_quotes_autor, name="all_quotes_autor"),
    path("quotes/all_quotes_one_tag/<int:tag_id><int:page>", views.all_quotes_one_tag, name="all_quotes_one_tag"),
    path("quotes/random_quote/", views.random_quote, name="random_quote"),
]

Django_hw/quotes_site/quotes_site/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('quotes.urls')),
    path('users/', include('users.urls'))
]

Django_hw/quotes_site/users/urls.py
from django.urls import path
from django.contrib.auth.views import PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView

from .forms import LoginForm
from .views import RegisterView, MyLoginView, MyLogoutView, ResetPasswordView

app_name = "users"

urlpatterns = [
    path('signup/', RegisterView.as_view(), name='register'),
    path('signin/', MyLoginView.as_view(
        template_name="users/signin.html",
        authentication_form=LoginForm,
        redirect_authenticated_user=True
    ), name='login'),
    path('logout/', MyLogoutView.as_view(
        template_name="users/logout.html",
    ), name='logout'),
    path('reset-password/', ResetPasswordView.as_view(), name='password_reset'),
    path('reset-password/done/', PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path('reset-password/confirm/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html',
                                          success_url='/users/reset-password/complete/'),
         name='password_reset_confirm'),
    path('reset-password/complete/',
         PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),
]

Django_hw/quotes_site/users/models.py
from django.db import models

# Create your models here.

Django_hw/quotes_site/users/forms.py
from django.forms import ModelForm, CharField, TextInput, EmailField, EmailInput, PasswordInput, Form
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, PasswordResetForm


class RegisterForm(UserCreationForm):
    username = CharField(max_length=100, min_length=5, required=True,
                         widget=TextInput(attrs={"class": "form-control"}))
    first_name = CharField(max_length=100, widget=TextInput(attrs={"class": "form-control"}))
    last_name = CharField(max_length=100, widget=TextInput(attrs={"class": "form-control"}))
    email = EmailField(max_length=100, widget=EmailInput(attrs={"class": "form-control"}))
    password1 = CharField(max_length=16, min_length=6, required=True,
                          widget=PasswordInput(attrs={"class": "form-control"}))
    password2 = CharField(max_length=16, min_length=6, required=True,
                          widget=PasswordInput(attrs={"class": "form-control"}))

    class Meta:
        model = User
        fields = ("username", "first_name", "last_name", "email", "password1", "password2")


class LoginForm(AuthenticationForm):
    username = CharField(max_length=100, min_length=5, required=True,
                         widget=TextInput(attrs={"class": "form-control"}))
    password = CharField(max_length=16, min_length=6, required=True,
                         widget=PasswordInput(attrs={"class": "form-control"}))

    class Meta:
        model = User
        fields = ("username", "password")


class MyPasswordResetForm(PasswordResetForm):
    email = EmailField(label="Email", max_length=100, widget=EmailInput(attrs={"class": "form-control"}))

    class Meta:
        model = User
        fields = ("email", )

Django_hw/quotes_site/users/views.py
from django.shortcuts import render, redirect
from django.views import View
from django.contrib import messages
from .forms import RegisterForm, MyPasswordResetForm
from django.contrib.auth.views import LoginView, LogoutView, PasswordResetView
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy


class MyLoginView(LoginView):
    extra_context = {"title": "QuoteHive: login"}


class MyLogoutView(LogoutView):
    extra_context = {"title": "QuoteHive: logout"}


# Create your views here.
class RegisterView(View):
    form_class = RegisterForm
    template_name = "users/signup.html"

    def get(self, request):
        return render(request, self.template_name, context={"form": self.form_class, "title": "QuoteHive: sign up"})

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data["username"]
            messages.success(request, f"Welcome {username}. Your account has been successfully created!")
            return redirect(to="users:login")
        return render(request, self.template_name, context={"form": form, "title": "QuoteHive: sign up"})


class ResetPasswordView(SuccessMessageMixin, PasswordResetView):
    form_class = MyPasswordResetForm
    template_name = 'users/password_reset.html'
    email_template_name = 'users/password_reset_email.html'
    html_email_template_name = 'users/password_reset_email.html'
    success_url = reverse_lazy('users:password_reset_done')
    success_message = "An email with instructions to reset your password has been sent to %(email)s."
    subject_template_name = 'users/password_reset_subject.txt'

Django_hw/quotes_site/users/templates/users/logout.html
{% extends "quotes/base.html" %}

{% block main %}
    <div class="px-4 pt-5 my-5 text-center border-bottom">
        <h1 class="my_display-4 text-body-emphasis text-center">See you later.</h1>
        <div class="col-lg-6 mx-auto">
            <p class="lead mb-4">Thank you for using our service.</p>
            <div class="d-grid gap-2 d-sm-flex justify-content-sm-center mb-5">
                <a href="{% url 'quotes:random_quote' %}"  class="btn btn-primary btn-lg px-4 me-sm-3">Random Quote</a>
                <a href="{% url 'users:login' %}" class="btn btn-outline btn-lg px-4">Sign in</a>
            </div>
        </div>
    </div>
{% endblock %}

Django_hw/quotes_site/users/templates/users/password_reset.html
{% extends "quotes/base.html" %}

{% block main %}
<main>

<div class="container col-xl-10 col-xxl-8 px-4 py-0 border-bottom">
    <h2 class="my_display-4 text-body-emphasis text-center">Password reset</h2>
    <div class="row align-items-center g-lg-2 py-5">
        <div class="col-md-10 mx-auto col-lg-5">
            <form method="post" class="p-4 p-md-5 border rounded-3 bg-body-tertiary">
                {% csrf_token %}
                <div class="form-floating mb-4 ">
                    {{ form.as_p }}
                    {% if form.errors.email %}
                    <div class="alert alert-danger py-1" role="alert">
                        <span>{{form.errors.email}}</span>
                    </div>
                    {% endif%}
                </div>
                <div class="d-grid gap-3 d-sm-flex justify-content-sm-center mb-3">
                    <button class="w-100 btn btn-lg btn-primary" type="submit">Request password reset</button>
                    <button class="w-100 btn btn-outline btn-lg px-4" type="reset">Reset</button>
                </div>
            </form>
        </div>
    </div>
</div>
</main>
{% endblock %}

Django_hw/quotes_site/users/templates/users/password_reset_complete.html
{% extends "quotes/base.html" %}

{% block main %}

<main>

    <div class="px-4 pt-2 my-5 text-center border-bottom">
        <h1 class="my_display-4 text-body-emphasis text-center">Password reset complete!</h1>
        <div class="col-lg-6 mx-auto">

            <div class="d-grid gap-2 d-sm-flex justify-content-sm-center mb-5">
                <a href="{% url 'users:login' %}"  class="btn btn-primary btn-lg px-4 me-sm-3">Sign in</a>
                <a href="{% url 'quotes:random_quote' %}"  class="btn btn-primary btn-lg px-4 me-sm-3">Random Quote</a>
            </div>
        </div>
    </div>

</main>

{% endblock %}

Django_hw/quotes_site/users/templates/users/password_reset_confirm.html
{% extends "quotes/base.html" %}

{% block main %}

<main>

    <div class="px-4 pt-2 my-3 text-center border-bottom">
        <div class="row align-items-center g-lg-2 py-5">
            <h1 class="my_display-4 text-body-emphasis text-center">Enter new password</h1>
            <div class="col-md-10 mx-auto col-lg-5">
                <form method="post" class="p-4 p-md-5 border rounded-3 bg-body-tertiary">
                    {% csrf_token %}
                    <div class="form-floating mb-4 ">
                        {{ form.as_p }}
                        {% if form.errors.email %}
                        <div class="alert alert-danger py-1" role="alert">
                            <span>{{form.errors.email}}</span>
                        </div>
                        {% endif%}
                    </div>
                    <div class="d-grid gap-3 d-sm-flex justify-content-sm-center mb-3">
                        <button class="w-100 btn btn-lg btn-primary" type="submit">Request password reset</button>
                        <button class="w-100 btn btn-outline btn-lg px-4" type="reset">Reset</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</main>
{% endblock %}

Django_hw/quotes_site/users/templates/users/password_reset_done.html
{% extends "quotes/base.html" %}

{% block main %}

<main>

    <div class="px-4 pt-2 my-5 text-center border-bottom">
        <h1 class="my_display-4 text-body-emphasis text-center">Password reset request sent</h1>
        <div class="col-lg-6 mx-auto">
            <p class="lead mb-4">We've emailed you with instructions on how to reset your password.</p>

            <div class="d-grid gap-2 d-sm-flex justify-content-sm-center mb-5">
                <a href="{% url 'users:login' %}"  class="btn btn-primary btn-lg px-4 me-sm-3">Sign in</a>
                <a href="{% url 'quotes:random_quote' %}"  class="btn btn-primary btn-lg px-4 me-sm-3">Random Quote</a>
            </div>
        </div>
    </div>

</main>

{% endblock %}

Django_hw/quotes_site/users/templates/users/password_reset_email.html
{% autoescape off %}

<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Password Reset Request</title>
</head>
<body>
<p>Dear {{ user.username }},</p>
<p>We have received a request to reset the password for your account. To proceed with the password reset, please follow
    the instructions below:</p>
<p>1. Click on the following link to access the password reset page:</p>
<p>
    <a target="_blank"
       href="{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}">
        Reset password
    </a>
</p>
<p>2. Once you are on the password reset page, you will be prompted to enter a new password for your account. Choose a
    strong and secure password that is not easily guessable.</p>
<p>If you did not initiate this password reset request, please disregard this email and take the necessary steps to
    secure your account.</p>
<p>Please note that this password reset link is valid for 1 day. After that period, you will need to request another
    password reset if you still need to change your password.</p>
<p>Thanks,</p>
<p>The Our Team</p>
{% endautoescape %}

Django_hw/quotes_site/users/templates/users/signin.html
{% extends "quotes/base.html" %}

{% block main %}
<h1 class="my_display-4 text-body-emphasis text-center">Sign in</h1>

<div class="container col-xl-10 col-xxl-8 px-4 py-0 border-bottom">
    <div class="row align-items-center g-lg-2 py-5">

        <div class="col-xl-10 col-xxl-8 mx-auto">
            {% if messages %}
            {% for msg in messages %}
            <div class="alert alert-warning col-md-6 mx-auto " role="alert">
                <span>{{msg}}</span>
            </div>
            {% endfor %}
            {% endif %}
        </div>
        <div class="col-md-10 mx-auto col-lg-5">
            {% if form.errors %}
            <div class="alert alert-danger" role="alert">
                <span>{{form.non_field_errors}}</span>
            </div>
            {% endif %}
            <form method="post" class="p-4 p-md-5 border rounded-3 bg-body-tertiary">

                {% csrf_token %}
                <div class="form-floating mb-4 ">
                    {{form.username}}
                    <label>User name</label>
                    <span>{{form.errors.username}}</span>
                </div>
                <div class="form-floating mb-4">
                    {{form.password}}
                    <label>Password</label>
                    <span>{{form.errors.password}}</span>
                </div>
                <div class="small text-center">
                    <a href="{% url 'users:password_reset' %}" class="text-center"><i>Forgot Password?</i></a>
                </div>
                <div class="d-grid gap-3 d-sm-flex justify-content-sm-center mb-3">
                    <button class="w-100 btn btn-lg btn-primary" type="submit">Submit</button>
                    <button class="w-100 btn btn-outline btn-lg px-4" type="reset">Reset</button>
                </div>

            </form>
        </div>
    </div>
</div>
{% endblock %}

Django_hw/quotes_site/users/templates/users/signup.html
{% extends "quotes/base.html" %}

{% block main %}
<h1 class="my_display-4 text-body-emphasis text-center">Sign up</h1>
<div class="container col-xl-10 col-xxl-8 px-4 py-0 border-bottom">
    <div class="row align-items-center g-lg-5 py-5">
        <div class="col-md-10 mx-auto col-lg-5">

            {% if form.errors %}
            {% if form.non_field_errors %}
            <div class="alert alert-danger" role="alert">
                <span>{{form.non_field_errors}}</span>
            </div>
            {% endif%}
            {% endif%}

            <form method="post" class="p-4 p-md-5 border rounded-3 bg-body-tertiary">
                {% csrf_token %}
                <div class="form-floating mb-3">
                    {{form.username}}
                    <label>User name</label>
                    {% if form.errors.username %}
                    <div class="alert alert-danger py-1" role="alert">
                        <span>{{form.errors.username}}</span>
                    </div>
                    {% endif%}
                </div>
                <div class="form-floating mb-3">
                    {{form.first_name}}
                    <label>First name</label>
                    {% if form.errors.first_name %}
                    <div class="alert alert-danger py-1" role="alert">
                        <span>{{form.errors.first_name}}</span>
                    </div>
                    {% endif%}
                </div>
                <div class="form-floating mb-3">
                    {{form.last_name}}
                    <label>Last name</label>
                    {% if form.errors.last_name %}
                    <div class="alert alert-danger py-1" role="alert">
                        <span>{{form.errors.last_name}}</span>
                    </div>
                    {% endif%}
                </div>
                <div class="form-floating mb-3">
                    {{form.email}}
                    <label>Email</label>
                    {% if form.errors.email %}
                    <div class="alert alert-danger py-1" role="alert">
                        <span>{{form.errors.email}}</span>
                    </div>
                    {% endif%}
                </div>
                <div class="form-floating mb-3">
                    {{form.password1}}
                    <label>Password</label>
                    {% if form.errors.password1 %}
                    <div class="alert alert-danger py-1" role="alert">
                        <span>{{form.errors.password1}}</span>
                    </div>
                    {% endif%}
                </div>
                <div class="form-floating mb-4">
                    {{form.password2}}
                    <label>Repeat password</label>
                    {% if form.errors.password2 %}
                    <div class="alert alert-danger py-1" role="alert">
                        <span>{{form.errors.password2}}</span>
                    </div>
                    {% endif%}
                </div>
                <div class="d-grid gap-3 d-sm-flex justify-content-sm-center mb-3">
                    <button class="w-100 btn btn-lg btn-primary" type="submit">Submit</button>
                    <button class="w-100 btn btn-outline btn-lg px-4" type="reset">Reset</button>
                </div>

            </form>
        </div>
    </div>
</div>
{% endblock %}