Django_hw/quotes_site/quotes/urls.py
from django.urls import path

from . import views

app_name = "quotes"

urlpatterns = [
    path("", views.home, name="home"),
    path("quotes/", views.show_quotes, name="quotes"),
    path('quotes/<int:page>', views.show_quotes, name="quotes_paginate"),
    path("quotes/add_author/", views.add_author, name="add_author"),
    path("quotes/add_quote/", views.add_quote, name="add_quote"),
    path("quotes/show_author/<int:aut_id>/", views.show_author, name="show_author"),
    path("quotes/show_author/all_quotes_autor/<int:aut_id><int:page>", views.all_quotes_autor, name="all_quotes_autor"),
    path("quotes/all_quotes_one_tag/<int:tag_id><int:page>", views.all_quotes_one_tag, name="all_quotes_one_tag"),
    path("quotes/random_quote/", views.random_quote, name="random_quote"),
]

Django_hw/quotes_site/quotes_site/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('quotes.urls')),
    path('users/', include('users.urls'))
]

Django_hw/quotes_site/users/urls.py
from django.urls import path
from django.contrib.auth.views import PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView

from .forms import LoginForm
from .views import RegisterView, MyLoginView, MyLogoutView, ResetPasswordView

app_name = "users"

urlpatterns = [
    path('signup/', RegisterView.as_view(), name='register'),
    path('signin/', MyLoginView.as_view(
        template_name="users/signin.html",
        authentication_form=LoginForm,
        redirect_authenticated_user=True
    ), name='login'),
    path('logout/', MyLogoutView.as_view(
        template_name="users/logout.html",
    ), name='logout'),
    path('reset-password/', ResetPasswordView.as_view(), name='password_reset'),
    path('reset-password/done/', PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path('reset-password/confirm/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html',
                                          success_url='/users/reset-password/complete/'),
         name='password_reset_confirm'),
    path('reset-password/complete/',
         PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),
]

Django_hw/quotes_site/quotes/models.py
from django.db import models


# Create your models here.
class Tag(models.Model):
    name = models.CharField(max_length=100, null=False, unique=True)

    def __str__(self):
        return f"{self.name}"


class Author(models.Model):
    fullname = models.CharField(max_length=50, null=False)
    born_date = models.CharField()
    born_location = models.CharField(max_length=300, null=False)
    description = models.CharField()

    def __str__(self):
        return self.fullname


class Quote(models.Model):
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    quote = models.CharField(null=False)
    tags = models.ManyToManyField(Tag)

    def __str__(self):
        return f"{self.quote}"

Django_hw/quotes_site/quotes/forms.py
from django.forms import ModelForm, CharField, TextInput, ModelMultipleChoiceField, Textarea, ModelChoiceField, Select
from django.core.exceptions import ValidationError
from taggit.forms import TagField

from .models import Author, Quote, Tag


class AuthorForm(ModelForm):
    fullname = CharField(max_length=100, min_length=5, required=True,
                         widget=TextInput(attrs={"class": "form-control"}))
    born_date = CharField(widget=TextInput(attrs={"class": "form-control"}))
    born_location = CharField(max_length=200, widget=TextInput(attrs={"class": "form-control"}))
    description = CharField(min_length=10, required=True,
                            widget=Textarea(attrs={"class": "form-control"}))

    class Meta:
        model = Author
        fields = ("fullname", "born_date", "born_location", "description")


class QuoteForm(ModelForm):
    author = ModelChoiceField(queryset=Author.objects.all().order_by("fullname"), widget=Select(attrs={'class': 'form-select'}))
    quote = CharField(widget=TextInput(attrs={"class": "form-control"}))
    tags = TagField(widget=TextInput(attrs={"class": "form-control"}))

    def clean_tags(self):
        tags = self.cleaned_data['tags']
        tags_list = []
        if tags:
            for tag in tags:
                tag = Tag.objects.get_or_create(name=tag.strip())
                tags_list.append(str(tag[0].id))
        return tags_list

    class Meta:
        model = Quote
        fields = ("author", "quote", "tags")

Django_hw/quotes_site/quotes/views.py
from random import choices

from django.db.models import Count
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from .forms import AuthorForm, QuoteForm
from .models import Quote, Author, Tag
from .utils import get_mongodb
from django.core.paginator import Paginator


def home(request):
    return render(request, "quotes/index.html", context={"title": "QuoteHive"})


def find_top_ten():
    tag_counts = Tag.objects.annotate(num_quotes=Count('quote')).order_by("-num_quotes")[:10]
    return tag_counts


def show_quotes(request, page=1):
    quotes = Quote.objects.all()
    per_page = 10
    paginator = Paginator(list(quotes), per_page)
    quotes_on_page = paginator.page(page)
    return render(request, "quotes/quotes.html",
                  context={"title": "QuoteHive", "quotes": quotes_on_page, "top_tags": find_top_ten()})


def show_author(request, aut_id):
    author = Author.objects.get(pk=aut_id)
    return render(request, "quotes/show_author.html", context={"title": "QuoteHive", "author": author})


def all_quotes_one_tag(request, tag_id, page=1):
    tag = Tag.objects.get(pk=tag_id)
    quotes = Quote.objects.filter(tags=tag_id).all()
    per_page = 3
    paginator = Paginator(list(quotes), per_page)
    quotes_on_page = paginator.page(page)
    return render(request, "quotes/all_quotes_one_tag.html",
                  context={"title": "QuoteHive", "quotes": quotes_on_page, "tag": tag, "top_tags": find_top_ten()})


def all_quotes_autor(request, aut_id, page=1):
    author = Author.objects.get(pk=aut_id)
    quotes = Quote.objects.filter(author=aut_id).all()
    per_page = 3
    paginator = Paginator(list(quotes), per_page)
    quotes_on_page = paginator.page(page)
    return render(request, "quotes/all_quotes_autor.html",
                  context={"title": "QuoteHive", "author": author, "quotes": quotes_on_page,
                           "top_tags": find_top_ten()})


def random_quote(request):
    quote = choices(Quote.objects.all())
    return render(request, "quotes/random_quote.html",
                  context={"title": "QuoteHive", "quote": quote[0], "top_tags": find_top_ten()})


@login_required
def add_author(request):
    if request.method == "POST":
        form = AuthorForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(to="quotes:quotes")
        else:
            return render(request, "quotes/add_author.html",
                          context={"form": AuthorForm(), "title": "QuoteHive: new author"})
    return render(request, "quotes/add_author.html", context={"form": AuthorForm(), "title": "QuoteHive: new author"})


@login_required
def add_quote(request):
    if request.method == "POST":
        form = QuoteForm(request.POST)

        if form.is_valid():
            form.save()
            return redirect(to="quotes:quotes")
        else:
            return render(request, "quotes/add_quote.html",
                          context={"form": QuoteForm(), "title": "QuoteHive: new quote"})
    return render(request, "quotes/add_quote.html", context={"form": QuoteForm(), "title": "QuoteHive: new quote"})

Django_hw/quotes_site/quotes/templates/quotes/add_author.html
{% extends "quotes/base.html" %}

{% block main %}
<h3 class="my_display-4 text-body-emphasis text-center">Add new author</h3>

<div class="container col-xl-10 col-xxl-8 px-4 py-0">
    <div class="row align-items-center g-lg-5 py-5">
        <div class="col-md-10 mx-auto col-lg-5">
            {% if form.errors %}
            <span class="alert alert-danger" role="alert">{{form.non_field_errors}}</span>
            {% endif %}

            <form method="POST" class="p-4 p-md-5 border rounded-3 bg-body-tertiary">
                {% csrf_token %}
                <div class="form-floating mb-3">
                    {{form.fullname}}
                    <label>Full name</label>
                    <span>{{form.errors.fullname}}</span>
                </div>
                <div class="form-floating mb-3">
                    {{form.born_date}}
                    <label>Born date</label>
                    <span>{{form.errors.born_date}}</span>
                </div>
                <div class="form-floating mb-3">
                    {{form.born_location}}
                    <label>Born location</label>
                    <span>{{form.errors.born_location}}</span>
                </div>
                <div class="form-floating mb-3">
                    {{form.description}}
                    <label>Description</label>
                    <span>{{form.errors.description}}</span>
                </div>
                <div class="d-grid gap-3 d-sm-flex justify-content-sm-center mb-3">
                    <button class="w-100 btn btn-lg btn-primary" type="submit">Submit</button>
                    <button class="w-100 btn btn-outline btn-lg px-4" type="reset">Reset</button>
                </div>

            </form>
        </div>
        <div class="col-md-10 mx-auto">
            <nav>
                <ul class="d-flex justify-content-between w-100 mb-1 px-5 col-md-6 mx-auto">

                    <a class="btn mb-1 mb-md-0 btn-outline "
                       href="{% url 'quotes:add_quote' %}">
                        Add quote
                    </a>
                    <a class="btn mb-1 mb-md-0 btn-outline"
                       href="{% url 'quotes:quotes' %}">
                        All quotes
                    </a>
                </ul>
            </nav>
        </div>
    </div>
</div>
{% endblock %}

Django_hw/quotes_site/quotes/templates/quotes/add_quote.html
{% extends "quotes/base.html" %}

{% block main %}
<h3 class="my_display-4 text-body-emphasis text-center">Add new quote</h3>

<div class="container col-xl-10 col-xxl-8 px-4 py-0">
    <div class="row align-items-center g-lg-5 py-5">
        <div class="col-md-10 mx-auto col-lg-5">
            {% if form.errors %}
            <span class="alert alert-danger" role="alert">{{form.non_field_errors}}</span>
            {% endif %}

            <form method="POST" class="p-4 p-md-5 border rounded-3 bg-body-tertiary">
                {% csrf_token %}
                <div class="form-floating mb-3">
                    {{form.author}}
                    <label>Author full name</label>
                    <span>{{form.errors.author}}</span>
                </div>
                <div class="form-floating mb-3">
                    {{form.quote}}
                    <label>Quote</label>
                    <span>{{form.errors.quote}}</span>
                </div>
                <div class="form-floating mb-3">
                    {{form.tags}}
                    <label>Tags</label>
                    <span>{{form.errors.tags}}</span>
                </div>
                <div class="d-grid gap-3 d-sm-flex justify-content-sm-center mb-2">
                    <button class="w-100 btn btn-lg btn-primary" type="submit">Submit</button>
                    <button class="w-100 btn btn-outline btn-lg px-4" type="reset">Reset</button>
                </div>
                {% if form.errors %}
                <span class="alert alert-danger" role="alert">{{form.non_field_errors}}</span>
                {% endif %}
            </form>
        </div>
        <div class="col-md-10 mx-auto">
            <nav>
                <ul class="d-flex justify-content-between w-100 mb-1 px-5 col-md-6 mx-auto">

                    <a class="btn mb-1 mb-md-0 btn-outline "
                       href="{% url 'quotes:add_author' %}">
                        Add author
                    </a>
                    <a class="btn mb-1 mb-md-0 btn-outline"
                       href="{% url 'quotes:quotes' %}">
                        All quotes
                    </a>
                </ul>
            </nav>
        </div>
    </div>
</div>
{% endblock %}

Django_hw/quotes_site/quotes/templates/quotes/all_quotes_autor.html
{% extends "quotes/base.html" %}
{% load extract %}

{% block main %}
<main>
    <div class="container">
        <div class="row mb-3">
            <div class="col-sm-6 col-lg-8 themed-grid-col">
                <h1 class="my_display-4 text-body-emphasis text-center">{{author.fullname}}</h1>

                {% for quote in quotes %}
                <div class="modal-content rounded-4 shadow">
                        <span class="text text-center" itemprop="text">
                            {{quote.quote}}
                        </span>
                    <div>
                        <a class="author" href="{% url 'quotes:show_author' quote.author.id %}"
                           title="{{quote.author.fullname}}">
                            {{quote.author.fullname}}
                        </a>
                    </div>
                    <div class="node__topics">
                        Tags:
                        {% for tag in quote.tags.all %}
                        <a class="btn mb-2 mb-md-0 btn-outline-danger btn-sm"
                           href="{% url 'quotes:all_quotes_one_tag' tag.id 1 %}">{{tag.name}}</a>
                        {% endfor %}
                    </div>
                </div>
                {% endfor %}


                <nav>
                    <ul class="d-flex justify-content-between w-100 mb-1 px-5 mx-auto">
                        {% if quotes.has_previous %}
                        <a class="btn mb-1 mb-md-0 btn-outline "
                           href="{% url 'quotes:all_quotes_autor' author.id quotes.previous_page_number %}">
                            ❮ Previous
                        </a>
                        {% endif %}
                        {% if quotes.has_next %}
                        <a class="{% if not quotes.has_previous %} btn mb-1 mb-md-0 btn-outline ml-auto {% else %} btn mb-1 mb-md-0 btn-outline {% endif %} "
                           href="{% url 'quotes:all_quotes_autor' author.id quotes.next_page_number %}">
                            Next ❯
                        </a>
                        {% endif %}
                    </ul>
                </nav>


            </div>


            <div class="col-6 col-lg-4 themed-grid-col">
                {% if user.is_authenticated %}
                <div class="d-grid gap-2 d-sm-flex justify-content-center mb-5">
                    <a href="{% url 'quotes:add_author' %}" class="btn btn-outline btn-lg px-4">Add author</a>
                    <a href="{% url 'quotes:add_quote' %}" class="btn btn-outline btn-lg px-4">Add quotes</a>
                </div>
                {% endif %}
                <div class="d-grid gap-3 justify-content-center mb-5">
                    <h3 class="text-top-tags">TOP 10 tags</h3>
                    <div class="d-grid gap-3 justify-content-center mb-5">
                        {% for tag in top_tags %}
                        <a class="btn mb-2 mb-md-0 btn-outline-danger btn-sm"
                           href="{% url 'quotes:all_quotes_one_tag' tag.id 1 %}">{{tag}}</a>
                        {% endfor %}
                    </div>
                </div>

            </div>
        </div>
    </div>


    <div class="px-4 pt-5 my-5 text-center border-bottom">

    </div>

</main>
{% endblock %}

Django_hw/quotes_site/quotes/templates/quotes/all_quotes_one_tag.html
{% extends "quotes/base.html" %}
{% load extract %}

{% block main %}
<main>
    <div class="container">
        <div class="row mb-3">
            <div class="col-sm-6 col-lg-8 themed-grid-col">
                <h1 class="my_display-4 text-body-emphasis text-center">"{{tag}}"</h1>

                {% for quote in quotes %}
                <div class="modal-content rounded-4 shadow">
                        <span class="text text-center" itemprop="text">
                            {{quote.quote}}
                        </span>
                    <div>
                        <a class="author" href="{% url 'quotes:show_author' quote.author.id %}"
                           title="{{quote.author.fullname}}">
                            {{quote.author.fullname}}
                        </a>
                    </div>
                    <div class="node__topics">
                        Tags:
                        {% for tag in quote.tags.all %}
                        <a class="btn mb-2 mb-md-0 btn-outline-danger btn-sm"
                           href="{% url 'quotes:all_quotes_one_tag' tag.id 1 %}">{{tag.name}}</a>
                        {% endfor %}
                    </div>
                </div>
                {% endfor %}


                <nav>
                    <ul class="d-flex justify-content-between w-100 mb-1 px-5 mx-auto">
                        {% if quotes.has_previous %}
                        <a class="btn mb-1 mb-md-0 btn-outline "
                           href="{% url 'quotes:all_quotes_one_tag' tag.id quotes.previous_page_number %}">
                            ❮ Previous
                        </a>
                        {% endif %}
                        {% if quotes.has_next %}
                        <a class="{% if not quotes.has_previous %} btn mb-1 mb-md-0 btn-outline ml-auto {% else %} btn mb-1 mb-md-0 btn-outline {% endif %} "
                           href="{% url 'quotes:all_quotes_one_tag' tag.id quotes.next_page_number %}">
                            Next ❯
                        </a>
                        {% endif %}
                    </ul>
                </nav>


            </div>


            <div class="col-6 col-lg-4 themed-grid-col">
                {% if user.is_authenticated %}
                <div class="d-grid gap-2 d-sm-flex justify-content-center mb-5">
                    <a href="{% url 'quotes:add_author' %}" class="btn btn-outline btn-lg px-4">Add author</a>
                    <a href="{% url 'quotes:add_quote' %}" class="btn btn-outline btn-lg px-4">Add quotes</a>
                </div>
                {% endif %}
                <div class="d-grid gap-3 justify-content-center mb-5">
                    <h3 class="text-top-tags">TOP 10 tags</h3>
                    <div class="d-grid gap-3 justify-content-center mb-5">
                        {% for tag in top_tags %}
                        <a class="btn mb-2 mb-md-0 btn-outline-danger btn-sm"
                           href="{% url 'quotes:all_quotes_one_tag' tag.id 1 %}">{{tag}}</a>
                        {% endfor %}
                    </div>
                </div>

            </div>
        </div>
    </div>


    <div class="px-4 pt-5 my-5 text-center border-bottom">

    </div>

</main>
{% endblock %}

Django_hw/quotes_site/quotes/templates/quotes/base.html
<!doctype html>

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <title>{{ title }}</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'quotes/style.css' %}">
    <link rel="shortcut icon" href="{% static 'quotes/img/icons8-honeybee-16.png' %}">


</head>
<body>

<div class="container">
    <footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
        <p class="col-md-4 mb-0 text-body-secondary">&copy; 2023 Quotes </p>

        <ul class="nav col-md-4 justify-content-end">
            <li class="nav-item"><a href="{% url 'quotes:home' %}" class="nav-link px-2 text-body-secondary">Home</a>
            </li>
            <li class="nav-item"><a href="{% url 'quotes:quotes' %}"
                                    class="nav-link px-2 text-body-secondary">Quotes</a></li>
            {% if not user.is_authenticated %}
            <li class="nav-item"><a href="{% url 'users:register' %}" class="nav-link px-2 text-body-secondary">Sign
                up</a></li>
            <li class="nav-item"><a href="{% url 'users:login' %}" class="nav-link px-2 text-body-secondary">Sign in</a>
            </li>
            {% endif %}
            {% if user.is_authenticated %}
            <li class="nav-item"><a href="{% url 'users:logout' %}" class="nav-link px-2 text-body-secondary">Logout</a>
            </li>
            {% endif %}
        </ul>
    </footer>
</div>

{% block main %}
{% endblock %}


</body>
</html>

Django_hw/quotes_site/quotes/templates/quotes/index.html
{% extends "quotes/base.html" %}

{% block main %}
<main>

    <div class="px-4 pt-2 my-5 text-center border-bottom">
        <h1 class="my_display-4 text-body-emphasis text-center">QuoteHive: A Hive of Inspiration and Wisdom</h1>
        <div class="col-lg-6 mx-auto">
            <p class="lead mb-4">This website is a collection of famous quotes from books and speeches by authors,
                politicians, artists, musicians, and other well-known personalities. It was created for quote
                enthusiasts and serves as a source of inspiration and motivation for people of all ages and interests.</p>

                <p class="lead mb-4">On the quotes page, you can find a randomly selected quote from the collection, as well as go to the
                pages with authors and tags. On the author pages, you can find information about the authors of the
                quotes.</p>

                <p class="lead mb-4">In addition, the site offers the possibility to add new authors and quotes through a special form, only
                for authenticated users.</p>

                <p class="lead mb-4">This is an interesting and engaging resource that inspires and broadens horizons in the fields of
                literature, art, politics, and other areas.</p>
            <div class="d-grid gap-2 d-sm-flex justify-content-sm-center mb-5">
                <a href="{% url 'quotes:random_quote' %}"  class="btn btn-primary btn-lg px-4 me-sm-3">Random Quote</a>
                {% if user.is_authenticated %}
                <a href="{% url 'quotes:add_quote' %}" class="btn btn-outline btn-lg px-4">Add quotes</a>
                {% endif%}
            </div>
        </div>
    </div>

</main>
{% endblock %}

Django_hw/quotes_site/quotes/templates/quotes/quotes.html
{% extends "quotes/base.html" %}
{% load extract %}

{% block main %}
<main>
    <div class="container">
        <div class="row mb-3">
            <div class="col-sm-6 col-lg-8 themed-grid-col">
                <h1 class="my_display-4 text-body-emphasis text-center">All quotes</h1>

                {% for quote in quotes %}
                <div class="modal-content rounded-4 shadow">
                        <span class="text text-center" itemprop="text">
                            {{quote.quote}}
                        </span>
                    <div>
                        <a class="author" href="{% url 'quotes:show_author' quote.author.id %}" title="{{quote.author.fullname}}">
                            {{quote.author.fullname}}
                        </a>
                    </div>
                    <div class="node__topics">
                        Tags:
                        {% for tag in quote.tags.all %}
                        <a class="btn mb-2 mb-md-0 btn-outline-danger btn-sm" href="{% url 'quotes:all_quotes_one_tag' tag.id 1 %}">{{tag.name}}</a>
                        {% endfor %}
                    </div>
                </div>
                {% endfor %}

                <nav>
                    <ul class="d-flex justify-content-between w-100 mb-1 px-5 mx-auto">
                        {% if quotes.has_previous %}
                        <a class="btn mb-1 mb-md-0 btn-outline "
                           href="{% url 'quotes:quotes_paginate' quotes.previous_page_number %}">
                            ❮ Previous
                        </a>
                        {% endif %}
                        {% if quotes.has_next %}
                        <a class="{% if not quotes.has_previous %} btn mb-1 mb-md-0 btn-outline ml-auto {% else %} btn mb-1 mb-md-0 btn-outline {% endif %} "
                           href="{% url 'quotes:quotes_paginate' quotes.next_page_number %}">
                            Next ❯
                        </a>
                        {% endif %}
                    </ul>
                </nav>
            </div>

            <div class="col-6 col-lg-4 themed-grid-col">
                {% if user.is_authenticated %}
                <div class="d-grid gap-2 d-sm-flex justify-content-center mb-5">
                    <a href="{% url 'quotes:add_author' %}" class="btn btn-outline btn-lg px-4">Add author</a>
                    <a href="{% url 'quotes:add_quote' %}" class="btn btn-outline btn-lg px-4">Add quotes</a>
                </div>
                {% endif %}
                <div class="d-grid gap-3 justify-content-center mb-5">
                    <h3 class="text-top-tags">TOP 10 tags</h3>
                    <div class="d-grid gap-3 justify-content-center mb-5">
                    {% for tag in top_tags %}
                    <a class="btn mb-2 mb-md-0 btn-outline-danger btn-sm" href="{% url 'quotes:all_quotes_one_tag' tag.id 1 %}">{{tag}}</a>
                    {% endfor %}
                    </div>
                </div>

            </div>
        </div>
    </div>


    <div class="px-4 pt-5 my-5 text-center border-bottom">

    </div>

</main>
{% endblock %}

Django_hw/quotes_site/quotes/templates/quotes/random_quote.html
{% extends "quotes/base.html" %}
{% load extract %}

{% block main %}
<main>
    <div class="container">
        <div class="row mb-3">
            <div class="col-sm-6 col-lg-8 themed-grid-col ">
                <div class="modal-content rounded-4 shadow">

                        <span class="text text-center" itemprop="text">
                            {{quote.quote}}
                        </span>
                    <div>
                        <a class="author" href="{% url 'quotes:show_author' quote.author.id %}"
                           title="{{quote.author.fullname}}">
                            {{quote.author.fullname}}
                        </a>
                    </div>
                    <div class="node__topics">
                        Tags:
                        {% for tag in quote.tags.all %}
                        <a class="btn mb-2 mb-md-0 btn-outline-danger btn-sm"
                           href="{% url 'quotes:all_quotes_one_tag' tag.id 1 %}">{{tag.name}}</a>
                        {% endfor %}
                    </div>
                </div>
            </div>

            <div class="col-6 col-lg-4 themed-grid-col">
                {% if user.is_authenticated %}
                <div class="d-grid gap-2 d-sm-flex justify-content-center mb-5">
                    <a href="{% url 'quotes:add_author' %}" class="btn btn-outline btn-lg px-4">Add author</a>
                    <a href="{% url 'quotes:add_quote' %}" class="btn btn-outline btn-lg px-4">Add quotes</a>
                </div>
                {% endif %}
                <div class="d-grid gap-3 justify-content-center mb-5">
                    <h3 class="text-top-tags">TOP 10 tags</h3>
                    <div class="d-grid gap-3 justify-content-center mb-5">
                        {% for tag in top_tags %}
                        <a class="btn mb-2 mb-md-0 btn-outline-danger btn-sm"
                           href="{% url 'quotes:all_quotes_one_tag' tag.id 1 %}">{{tag}}</a>
                        {% endfor %}
                    </div>
                </div>

            </div>
        </div>
    </div>


    <div class="px-4 pt-5 my-5 text-center border-bottom">

    </div>

</main>
{% endblock %}

Django_hw/quotes_site/quotes/templates/quotes/show_author.html
{% extends "quotes/base.html" %}

{% block main %}
<main>

    <div class="px-4 pt-2 my-5 text-center border-bottom">
        <h3 class="my_display-4 text-body-emphasis text-center">{{author.fullname}}</h3>
        <div class="col-lg-9 mx-auto">
            <p class="lead mb-4">Born: {{author.born_date}} {{author.born_location}}</p>
            <p class="description_text text-justify">{{author.description}}</p>


            <div class="d-grid gap-2 d-sm-flex justify-content-sm-center mb-5">
                <a href="{% url 'quotes:all_quotes_autor' author.id 1 %}" class="btn btn-primary btn-lg px-4 me-sm-3">All quotes author</a>
                <a href="{% url 'quotes:quotes' %}"  class="btn btn-outline btn-lg px-4">Back to quotes</a>
            </div>
        </div>
    </div>

</main>
{% endblock %}